function subjT = subjTnaming

    %% Katie's organization of STATIC data - VALIDATION TRIALS

    subjT{1,1} = 'TAXO';
    temp.day = {'10_10';'10_12';'10_15';'10_17';'10_25'};
    temp.files{1,1} = {'qs', 'taxoaa';
        'nw1', 'taxoab'; 'nw2', 'taxoai';
        'zt1', 'taxoac'; 'zt2', 'taxoah';
        'ga1', 'taxoaf'; 'ga2', 'taxoag'};
    temp.files{2,1} = {'qs', 'taxoba';
        'nw1', 'taxobf'; 'nw2', 'taxobg';
        'zt1', 'taxobd'; 'zt2', 'taxobi';
        'ga1', 'taxobe'; 'ga2', 'taxobh'};
    temp.files{3,1} = {'qs', 'taxoca';
        'nw1', 'taxocd'; 'nw2', 'taxoci';
        'zt1', 'taxocf'; 'zt2', 'taxocg';
        'ga1', 'taxoce'; 'ga2', 'taxoch'};
    temp.files{4,1} = {'qs', 'taxoda';
        'nw1', 'taxode'; 'nw2', 'taxodf';
        'zt1', 'taxodd'; 'zt2', 'taxodg';
        'ga1', 'taxodc'; 'ga2', 'taxodh'};
    temp.files{5,1} = {'qs', 'taxoea';
        'nw1', 'taxoee'; 'nw2', 'taxoef';
        'zt1', 'taxoec'; 'zt2', 'taxoeh';
        'ga1', 'taxoed'; 'ga2', 'taxoeg'};
    subjT{1,2} = temp;

    subjT{2,1} = 'TBXR';
    temp.day = {'11_1';'11_5';'11_7';'11_14';'11_19';'11_28'};
    temp.files{1,1} = {'qs', 'tbxraa';
        'nw1', 'tbxrad'; 'nw2', 'tbxrae';
        'zt1', 'tbxrab'; 'zt2', 'tbxrag';
        'ga1', 'tbxrac'; 'ga2', 'tbxraf'};
    temp.files{2,1} = {'qs', 'tbxrba';
        'nw1', 'tbxrbc'; 'nw2', 'tbxrbh';
        'zt1', 'tbxrbe'; 'zt2', 'tbxrbf';
        'ga1', 'tbxrbd'; 'ga2', 'tbxrbg'};
    temp.files{3,1} = {'qs', 'tbxrca';
        'nw1', 'tbxrcc'; 'nw2', 'tbxrci';
        'zt1', 'tbxrce'; 'zt2', 'tbxrch';
        'ga1', 'tbxrcf'; 'ga2', 'tbxrcg'};
    temp.files{4,1} = {'qs', 'tbxrda';
        'nw1', 'tbxrde'; 'nw2', 'tbxrdf';
        'zt1', 'tbxrdc'; 'zt2', 'tbxrdh';
        'ga1', 'tbxrdd'; 'ga2', 'tbxrdg'};
    temp.files{5,1} = {'qs', 'tbxrea';
        'nw1', 'tbxree'; 'nw2', 'tbxref';
        'zt1', 'tbxred'; 'zt2', 'tbxreg';
        'ga1', 'tbxrec'; 'ga2', 'tbxreh'};
    temp.files{6,1} = {'qs', 'tbxrfa';
        'nw1', 'tbxrfc'; 'nw2', 'tbxrfh';
        'zt1', 'tbxrfd'; 'zt2', 'tbxrfg';
        'ga1', 'tbxrfe'; 'ga2', 'tbxrff'};
    subjT{2,2} = temp;

    subjT{3,1} = 'TCYA';
    temp.day = {'4_30';'5_10';'5_14';'5_16';'5_21';'5_23'};
    temp.files{1,1} = {'qs', 'tcyaaa';
        'nw1', 'tcyaad'; 'nw2', 'tcyaae';
        'zt1', 'tcyaac'; 'zt2', 'tcyaaf';
        'ga1', 'tcyaab'; 'ga2', 'tcyaag'};
    temp.files{2,1} = {'qs', 'tcyaba';
        'nw1', 'tcyabe'; 'nw2', 'tcyabf';
        'zt1', 'tcyabd'; 'zt2', 'tcyabg';
        'ga1', 'tcyabc'; 'ga2', 'tcyabh'};
    temp.files{3,1} = {'qs', 'tcyaca';
        'nw1', 'tcyacd'; 'nw2', 'tcyaci';
        'zt1', 'tcyace'; 'zt2', 'tcyach';
        'ga1', 'tcyacf'; 'ga2', 'tcyacg'};
    temp.files{4,1} = {'qs', 'tcyada';
        'nw1', 'tcyade'; 'nw2', 'tcyadf';
        'zt1', 'tcyadc'; 'zt2', 'tcyadh';
        'ga1', 'tcyadd'; 'ga2', 'tcyadg'};
    temp.files{5,1} = {'qs', 'tcyaea';
        'nw1', 'tcyaef'; 'nw2', 'tcyaeg';
        'zt1', 'tcyaee'; 'zt2', 'tcyaeh';
        'ga1', 'tcyaed'; 'ga2', 'tcyaei'};
    temp.files{6,1} = {'qs', 'tcyafa';
        'nw1', 'tcyafd'; 'nw2', 'tcyafi';
        'zt1', 'tcyaff'; 'zt2', 'tcyafg';
        'ga1', 'tcyafe'; 'ga2', 'tcyafh'};
    subjT{3,2} = temp;

    subjT{4,1} = 'TDEB';
    temp.day = {'6_14';'6_18';'6_21';'6_24';'6_26';'7_2'};
    temp.files{1,1} = {'qs', 'tdebaa';
        'nw1', 'tdebab'; 'nw2', 'tdebag';
        'zt1', 'tdebac'; 'zt2', 'tdebaf';
        'ga1', 'tdebad'; 'ga2', 'tdebae'};
    temp.files{2,1} = {'qs', 'tdebba';
        'nw1', 'tdebbc'; 'nw2', 'tdebbh';
        'zt1', 'tdebbe'; 'zt2', 'tdebbf';
        'ga1', 'tdebbd'; 'ga2', 'tdebbg'};
    temp.files{3,1} = {'qs', 'tdebca';
        'nw1', 'tdebcc'; 'nw2', 'tdebch';
        'zt1', 'tdebce'; 'zt2', 'tdebcf';
        'ga1', 'tdebcd'; 'ga2', 'tdebcg'};
    temp.files{4,1} = {'qs', 'tdebda';
        'nw1', 'tdebdf'; 'nw2', 'tdebdg';
        'zt1', 'tdebde'; 'zt2', 'tdebdh';
        'ga1', 'tdebdd'; 'ga2', 'tdebdi'};
    temp.files{5,1} = {'qs', 'tdebea';
        'nw1', 'tdebee'; 'nw2', 'tdebef';
        'zt1', 'tdebec'; 'zt2', 'tdebeh';
        'ga1', 'tdebed'; 'ga2', 'tdebeg'};
    temp.files{6,1} = {'qs', 'tdebfa';
        'nw1', 'tdebfd'; 'nw2', 'tdebfi';
        'zt1', 'tdebfe'; 'zt2', 'tdebfh';
        'ga1', 'tdebff'; 'ga2', 'tdebfg'};
    subjT{4,2} = temp;

    subjT{5,1} = 'TEBX';
    temp.day = {'7_18';'7_23';'7_25';'7_27';'8_1';'8_4'};
    temp.files{1,1} = {'qs', 'tebxba';
        'nw1', 'tebxbd'; 'nw2', 'tebxbe';
        'zt1', 'tebxbb'; % 'zt2', 'tebxbh';
        'ga1', 'tebxbc'; 'ga2', 'tebxbh'};
    temp.files{2,1} = {'qs', 'tebxca';
        'nw1', 'tebxcd'; 'nw2', 'tebxci';
        'zt1', 'tebxcf'; 'zt2', 'tebxcg';
        'ga1', 'tebxce'; 'ga2', 'tebxch'};
    temp.files{3,1} = {'qs', 'tebxda';
        'nw1', 'tebxdc'; 'nw2', 'tebxdh';
        'zt1', 'tebxdd'; 'zt2', 'tebxdg';
        'ga1', 'tebxde'; 'ga2', 'tebxdf'};
    temp.files{4,1} = {'qs', 'tebxea';
        'nw1', 'tebxef'; 'nw2', 'tebxeg';
        'zt1', 'tebxee'; 'zt2', 'tebxeh';
        'ga1', 'tebxec'; 'ga2', 'tebxei'};
    temp.files{5,1} = {'qs', 'tebxfa';
        'nw1', 'tebxff'; 'nw2', 'tebxfg';
        'zt1', 'tebxfe'; 'zt2', 'tebxfh';
        'ga1', 'tebxfd'; 'ga2', 'tebxfi'};
    temp.files{6,1} = {'qs', 'tebxga';
        'nw1', 'tebxgc'; 'nw2', 'tebxgh';
        'zt1', 'tebxgd'; 'zt2', 'tebxgg';
        'ga1', 'tebxge'; 'ga2', 'tebxgf'};
    subjT{5,2} = temp;

    %% Katie's organization of CONTINUED data - VALIDATION TRIALS

    subjT{6,1} = 'PAWN';
    temp.day = {'10_3';'10_7';'10_9';'10_19';'10_25';'11_4'};
    temp.files{1,1} = {'qs', 'pawnaa';
        'nw1', 'pawnab'; 'nw2', 'pawnah';
        'zt1', 'pawnae'; 'zt2', 'pawnaf';
        'ga1', 'pawnad'; 'ga2', 'pawnag'};
    temp.files{2,1} = {'qs', 'pawncf';
        'nw1', 'pawncg'; 'nw2', 'pawncn';
        'zt1', 'pawnci'; 'zt2', 'pawncl';
        'ga1', 'pawnch'; 'ga2', 'pawncm';
        'o41', 'pawncj'; 'o42', 'pawnck'};
    temp.files{3,1} = {'qs', 'pawnde';
        'nw1', 'pawndj'; 'nw2', 'pawndk';
        'zt1', 'pawndi'; 'zt2', 'pawndl';
        'ga1', 'pawndg'; 'ga2', 'pawndn';
        'o41', 'pawndh'; 'o42', 'pawndm';
        'o81', 'pawndf'; 'o82', 'pawndo'};
    temp.files{4,1} = {'qs', 'pawnea';
        'nw1', 'pawnej'; 'nw2', 'pawnek';
        'zt1', 'pawneg'; 'zt2', 'pawnen';
        'ga1', 'pawneh'; 'ga2', 'pawnem';
        'o41', 'pawnee'; 'o42', 'pawnep';
        'o81', 'pawnei'; 'o82', 'pawnel';
        'o121','pawnef'; 'o122','pawneo'};
    temp.files{5,1} = {'qs', 'pawnfa';
        'nw1', 'pawnfk'; 'nw2', 'pawnfl';
        'zt1', 'pawnfe'; 'zt2', 'pawnfs';
        'ga1', 'pawnff'; 'ga2', 'pawnfr';
        'o41', 'pawnfi'; 'o42', 'pawnfn';
        'o81', 'pawnfh'; 'o82', 'pawnfp';
        'o121','pawnfj'; 'o122','pawnfm';
        'o161','pawnfg'; 'o162','pawnfq'};
    temp.files{6,1} = {'qs', 'pawnga';
        'nw1', 'pawngc'; 'nw2', 'pawngm';
        'zt1', 'pawngf'; 'zt2', 'pawngi';
        'ga1', 'pawngg'; 'ga2', 'pawngh';
        'o41', 'pawnge'; 'o42', 'pawngj';
        'o201','pawngd'; 'o202', 'pawngl'};
    subjT{6,2} = temp;
    clear temp

    subjT{7,1} = 'PBPK';
    temp.day = {'10_23';'10_26';'10_28';'11_2';'11_4';'11_8'};
    temp.files{1,1} = {'qs', 'pbpkaa';
        'nw1', 'pbpkab'; 'nw2', 'pbpkag';
        'zt1', 'pbpkac'; 'zt2', 'pbpkaf';
        'ga1', 'pbpkad'; 'ga2', 'pbpkae'};
    temp.files{2,1} = {'qs', 'pbpkba';
        'nw1', 'pbpkbf'; 'nw2', 'pbpkbg';
        'zt1', 'pbpkbe'; 'zt2', 'pbpkbh';
        'ga1', 'pbpkbc'; 'ga2', 'pbpkbj';
        'o41', 'pbpkbd'; 'o42', 'pbpkbi'};
    temp.files{3,1} = {'qs', 'pbpkca';
        'nw1', 'pbpkcg'; 'nw2', 'pbpkch';
        'zt1', 'pbpkcd'; 'zt2', 'pbpkck';
        'ga1', 'pbpkcf'; 'ga2', 'pbpkci';
        'o41', 'pbpkce'; 'o42', 'pbpkcj';
        'o81', 'pbpkcc'; 'o82', 'pbpkcl'};
    temp.files{4,1} = {'qs', 'pbpkda';
        'nw1', 'pbpkdc'; 'nw2', 'pbpkdl';
        'zt1', 'pbpkdf'; 'zt2', 'pbpkdi';
        'ga1', 'pbpkdd'; 'ga2', 'pbpkdk';
        'o41', 'pbpkdg'; 'o42', 'pbpkdh';
        'o121','pbpkde'; 'o122','pbpkdj'};
    temp.files{5,1} = {'qs', 'pbpkea';
        'nw1', 'pbpkeg'; 'nw2', 'pbpkeh';
        'zt1', 'pbpked'; 'zt2', 'pbpkek';
        'ga1', 'pbpkef'; 'ga2', 'pbpkei';
        'o41', 'pbpkec'; 'o42', 'pbpkel';
        'o161','pbpkee'; 'o162','pbpkej'};
    temp.files{6,1} = {'qs', 'pbpkfa';
        'nw1', 'pbpkfi'; 'nw2', 'pbpkfj';
        'zt1', 'pbpkff'; 'zt2', 'pbpkfm';
        'ga1', 'pbpkfg'; 'ga2', 'pbpkfl';
        'o41', 'pbpkfh'; 'o42', 'pbpkfk';
        'o201','pbpkfe'; 'o202','pbpkfo'};
    subjT{7,2} = temp;
    clear temp

    subjT{8,1} = 'PCYC';
    temp.day = {'2_6';'2_10';'2_13';'2_20';'2_27';'3_4'};
    temp.files{1,1} = {'qs', 'pcycaa';
        'nw1', 'pcycad'; 'nw2', 'pcycae';
        'zt1', 'pcycab'; 'zt2', 'pcycag';
        'ga1', 'pcycac'; 'ga2', 'pcycaf'};
    temp.files{2,1} = {'qs', 'pcycba';
        'nw1', 'pcycbf'; 'nw2', 'pcycbm';
        'zt1', 'pcycbh'; 'zt2', 'pcycbk';
        'ga1', 'pcycbg'; 'ga2', 'pcycbl';
        'o41', 'pcycbi'; 'o42', 'pcycbj'};
    temp.files{3,1} = {'qs', 'pcycca';
        'nw1', 'pcycch'; 'nw2', 'pcycci';
        'zt1', 'pcyccf'; 'zt2', 'pcycck';
        'ga1', 'pcycce'; 'ga2', 'pcyccl';
        'o41', 'pcyccd'; 'o42', 'pcyccm';
        'o81', 'pcyccg'; 'o82', 'pcyccj'};
    temp.files{4,1} = {'qs', 'pcycda';
        'nw1', 'pcycdh'; 'nw2', 'pcycdi';
        'zt1', 'pcycdf'; 'zt2', 'pcycdk';
        'ga1', 'pcycdg'; 'ga2', 'pcycdj';
        'o41', 'pcycde'; 'o42', 'pcycdl';
        'o121', 'pcycdd'; 'o82', 'pcycdm'};
    temp.files{5,1} = {'qs', 'pcycfa';
        'nw1', 'pcycfc'; 'nw2', 'pcycfl';
        'zt1', 'pcycfd'; 'zt2', 'pcycfk';
        'ga1', 'pcycff'; 'ga2', 'pcycfi';
        'o41', 'pcycfg'; 'o42', 'pcycfh';
        'o161','pcycfe'; 'o162','pcycfj'};
    temp.files{6,1} = {'qs', 'pcycga';
        'nw1', 'pcycgg'; 'nw2', 'pcycgh';
        'zt1', 'pcycgd'; 'zt2', 'pcycgk';
        'ga1', 'pcycgf'; 'ga2', 'pcycgi';
        'o41', 'pcycge'; 'o42', 'pcycgj';
        'o201','pcycgc';'o202', 'pcycgl'};
    subjT{8,2} = temp;
    clear temp

    subjT{9,1} = 'PDUL';
    temp.day = {'4_24';'5_1';'5_8';'5_15';'5_17';'5_22'};
    temp.files{1,1} = {'qs', 'pdulaa';
%         'nw1', 'pdulab'; 'nw2', 'pdulah';
        'nw2', 'pdulah';
        'zt1', 'pdulac'; 'zt2', 'pdulag';
        'ga1', 'pdulad'; 'ga2', 'pdulaf'};
    temp.files{2,1} = {'qs', 'pdulba';
        'nw1', 'pdulbd'; 'nw2', 'pdulbk';
        'zt1', 'pdulbf'; 'zt2', 'pdulbi';
        'ga1', 'pdulbe'; 'ga2', 'pdulbj';
        'o41', 'pdulbg'; 'o42', 'pdulbh'};
    temp.files{3,1} = {'qs', 'pdulca';
        'nw1', 'pdulch'; 'nw2', 'pdulci';
        'zt1', 'pdulcf'; 'zt2', 'pdulck';
        'ga1', 'pdulcd'; 'ga2', 'pdulcm';
        'o41', 'pdulcg'; 'o42', 'pdulcj';
        'o81', 'pdulce'; 'o82', 'pdulcl'};
    temp.files{4,1} = {'qs', 'pdulda';
        'nw1', 'pduldc'; 'nw2', 'pduldm';
        'zt1', 'pdulde'; 'zt2', 'pduldl';
        'ga1', 'pduldh'; 'ga2', 'pduldi';
        'o41', 'pduldf'; 'o42', 'pduldk';
        'o121','pduldg'; 'o122','pduldj'};
    temp.files{5,1} = {'qs', 'pdulea';
        'nw1', 'pduled'; 'nw2', 'pdulem';
        'zt1', 'pdulef'; 'zt2', 'pdulek';
        'ga1', 'pduleg'; 'ga2', 'pdulej';
        'o41', 'pduleh'; 'o42', 'pdulei';
        'o161','pdulee'; 'o162','pdulel'};
    temp.files{6,1} = {'qs', 'pdulfa';
        'nw1', 'pdulfh'; 'nw2', 'pdulfi';
        'zt1', 'pdulfg'; 'zt2', 'pdulfj';
        'ga1', 'pdulff'; 'ga2', 'pdulfk';
        'o41', 'pdulfd'; 'o42', 'pdulfm';
        'o201','pdulfe'; 'o202','pdulfl'};
    subjT{9,2} = temp;
    clear temp

    subjT{10,1} = 'PEFM';
    temp.day = {'7_21';'7_23';'7_30';'8_1';'8_3';'8_5'};
    temp.files{1,1} = {'qs', 'pefmaa';
        'nw1', 'pefmab'; 'nw2', 'pefmag';
        'zt1', 'pefmac'; 'zt2', 'pefmaf';
        'ga1', 'pefmad'; 'ga2', 'pefmae'};
    temp.files{2,1} = {'qs', 'pefmba';
        'nw1', 'pefmbe'; 'nw2', 'pefmbl';
        'zt1', 'pefmbh'; 'zt2', 'pefmbi';
        'ga1', 'pefmbg'; 'ga2', 'pefmbj';
        'o41', 'pefmbf'; 'o42', 'pefmbk'};
    temp.files{3,1} = {'qs', 'pefmca';
        'nw1', 'pefmcc'; 'nw2', 'pefmcl';
        'zt1', 'pefmce'; 'zt2', 'pefmcj';
        'ga1', 'pefmcd'; 'ga2', 'pefmck';
        'o41', 'pefmcg'; 'o42', 'pefmch';
        'o81', 'pefmcf'; 'o82', 'pefmci'};
    temp.files{4,1} = {'qs', 'pefmda';
        'nw1', 'pefmdh'; 'nw2', 'pefmdi';
        'zt1', 'pefmdf'; 'zt2', 'pefmdk';
        'ga1', 'pefmdd'; 'ga2', 'pefmdm';
        'o41', 'pefmdg'; 'o42', 'pefmdj';
        'o121','pefmde'; 'o122','pefmdl'};
    temp.files{5,1} = {'qs', 'pefmea';
        'nw1', 'pefmee'; 'nw2', 'pefmen';
        'zt1', 'pefmeh'; 'zt2', 'pefmek';
        'ga1', 'pefmef'; 'ga2', 'pefmem';
        'o41', 'pefmeg'; 'o42', 'pefmel';
        'o161','pefmei'; 'o162','pefmej'};
    temp.files{6,1} = {'qs', 'pefmfa';
        'nw1', 'pefmfi'; 'nw2', 'pefmfj';
        'zt1', 'pefmfg'; 'zt2', 'pefmfl';
        'ga1', 'pefmff'; 'ga2', 'pefmfm';
        'o41', 'pefmfh'; 'o42', 'pefmfk';
        'o201','pefmfe'; 'o202','pefmfn'};
    subjT{10,2} = temp;
    clear temp

    %% Katie's organization of RE-OPT data - VALIDATION TRIALS

    subjT{11,1} = 'EAON';
    temp.day = {'11_3';'11_6';'11_13';'11_20';'12_7';'12_16'}; %;'12_18'};
    temp.files{1,1} = {'qs', 'eaonag';
        'nw1', 'eaonad'; 'nw2', 'eaonae';
        'zt1', 'eaonac'; 'zt2', 'eaonaf';
        'ga1', 'eaonab'; 'ga2', 'eaonah'};
    temp.files{2,1} = {'qs', 'eaonba';
        'nw1', 'eaonbh'; 'nw2', 'eaonbi';
        'zt1', 'eaonbg'; 'zt2', 'eaonbj';
        'ga1', 'eaonbf'; 'ga2', 'eaonbk';
        'o41', 'eaonbe'; 'o42', 'eaonbl'};
    temp.files{3,1} = {'qs', 'eaonca';
        'nw1', 'eaoncc'; 'nw2', 'eaoncl';
        'zt1', 'eaoncd'; 'zt2', 'eaonck';
        'ga1', 'eaoncf'; 'ga2', 'eaonci';
        'o41', 'eaonce'; 'o42', 'eaoncj';
        'o81', 'eaoncg'; 'o82', 'eaonch'};
    temp.files{4,1} = {'qs', 'eaonda';
        'nw1', 'eaondc'; 'nw2', 'eaondl';
        'zt1', 'eaonde'; 'zt2', 'eaondj';
        'ga1', 'eaondg'; 'ga2', 'eaondh';
        'o41', 'eaondd'; 'o42', 'eaondk';
        'o81', 'eaondf'; 'o82', 'eaondi'};
    temp.files{5,1} = {'qs', 'eaonea';
        'nw1', 'eaoneg'; 'nw2', 'eaonep';
        'zt1', 'eaonek'; 'zt2', 'eaonel';
        'ga1', 'eaonej'; 'ga2', 'eaonem';
        'o41', 'eaoneh'; 'o42', 'eaoneo';
        'o81', 'eaonei'; 'o82', 'eaonen'};
    temp.files{6,1} = {'qs', 'eaonfa';
        'nw1', 'eaonfg'; 'nw2', 'eaonfh';
        'zt1', 'eaonfe'; 'zt2', 'eaonfj';
        'ga1', 'eaonfd'; 'ga2', 'eaonfk';
        'o41', 'eaonff'; 'o42', 'eaonfi';
        'o81', 'eaonfc'; 'o82', 'eaonfl'};
%     temp.files{7,1} = {'qs', 'eaonga';
%         'nw1', 'eaongi'; 'nw2', 'eaongj';
%         'zt1', 'eaongf'; 'zt2', 'eaongm';
%         'ga1', 'eaonge'; 'ga2', 'eaongn';
% %         'o41', 'eaongg'; 'o42', 'eaongl';
%         'o81', 'eaongh'; 'o82', 'eaongk'};
    subjT{11,2} = temp;
    clear temp

    subjT{12,1} = 'EBOA';
    temp.day = {'11_26';'12_3';'12_6';'12_13';'12_17';'12_19'};
    temp.files{1,1} = {'qs', 'eboaaa';
        'nw1', 'eboaad'; 'nw2', 'eboaae';
        'zt1', 'eboaab'; 'zt2', 'eboaah';
        'ga1', 'eboaac'; 'ga2', 'eboaag'};
    temp.files{2,1} = {'qs', 'eboaba';
        'nw1', 'eboabc'; 'nw2', 'eboabk';
        'zt1', 'eboabe'; 'zt2', 'eboabh';
        'ga1', 'eboabd'; 'ga2', 'eboabj';
        'o41', 'eboabf'; 'o42', 'eboabg'};
    temp.files{3,1} = {'qs', 'eboaca';
        'nw1', 'eboacg'; 'nw2', 'eboach';
        'zt1', 'eboacd'; 'zt2', 'eboack';
        'ga1', 'eboace'; 'ga2', 'eboacj';
        'o41', 'eboacc'; 'o42', 'eboacl';
        'o81', 'eboacf'; 'o82', 'eboaci'};
    temp.files{4,1} = {'qs', 'eboadd';
        'nw1', 'eboadj'; 'nw2', 'eboadk';
        'zt1', 'eboadg'; 'zt2', 'eboado';
        'ga1', 'eboadi'; 'ga2', 'eboadl';
        'o41', 'eboadf'; 'o42', 'eboadp';
        'o81', 'eboadh'; 'o82', 'eboadn'};
    temp.files{5,1} = {'qs', 'eboaea';
        'nw1', 'eboaeg'; 'nw2', 'eboaeh';
        'zt1', 'eboaee'; 'zt2', 'eboaej';
        'ga1', 'eboaed'; 'ga2', 'eboaek';
        'o41', 'eboaec'; 'o42', 'eboael';
        'o81', 'eboaef'; 'o82', 'eboaei'};
    temp.files{6,1} = {'qs', 'eboafa';
        'nw1', 'eboafd'; 'nw2', 'eboafm';
        'zt1', 'eboafh'; 'zt2', 'eboafi';
        'ga1', 'eboafe'; 'ga2', 'eboafl';
        'o41', 'eboaff'; 'o42', 'eboafk';
        'o81', 'eboafg'; 'o82', 'eboafj'};
    subjT{12,2} = temp;
    clear temp

    subjT{13,1} = 'ECAZ';
    temp.day = {'4_3';'4_5';'4_9';'4_12';'4_16';'4_19'};
    temp.files{1,1} = {'qs', 'ecazaa';
        'nw1', 'ecazad'; 'nw2', 'ecazae';
        'zt1', 'ecazab'; 'zt2', 'ecazah';
        'ga1', 'ecazac'; 'ga2', 'ecazag'};
    temp.files{2,1} = {'qs', 'ecazba';
        'nw1', 'ecazbc'; 'nw2', 'ecazbj';
        'zt1', 'ecazbd'; 'zt2', 'ecazbi';
        'ga1', 'ecazbf'; 'ga2', 'ecazbg';
        'o41', 'ecazbe'; 'o42', 'ecazbh'};
    temp.files{3,1} = {'qs', 'ecazca';
        'nw1', 'ecazcc'; 'nw2', 'ecazcl';
        'zt1', 'ecazce'; 'zt2', 'ecazcj';
        'ga1', 'ecazcd'; 'ga2', 'ecazck';
        'o41', 'ecazcg'; 'o42', 'ecazch';
        'o81', 'ecazcf'; 'o82', 'ecazci'};
    temp.files{4,1} = {'qs', 'ecazda';
        'nw1', 'ecazdg'; 'nw2', 'ecazdh';
        'zt1', 'ecazdc'; 'zt2', 'ecazdl';
        'ga1', 'ecazde'; 'ga2', 'ecazdj';
        'o41', 'ecazdf'; 'o42', 'ecazdi';
        'o81', 'ecazdd'; 'o82', 'ecazdk'};
    temp.files{5,1} = {'qs', 'ecazea';
        'nw1', 'ecazec'; 'nw2', 'ecazel';
        'zt1', 'ecazed'; 'zt2', 'ecazek';
        'ga1', 'ecazee'; 'ga2', 'ecazej';
        'o41', 'ecazeg'; 'o42', 'ecazeh';
        'o81', 'ecazef'; 'o82', 'ecazei'};
    temp.files{6,1} = {'qs', 'ecazfa';
        'nw1', 'ecazfc'; 'nw2', 'ecazfl';
        'zt1', 'ecazfe'; 'zt2', 'ecazfj';
        'ga1', 'ecazff'; 'ga2', 'ecazfi';
        'o41', 'ecazfg'; 'o42', 'ecazfh';
        'o81', 'ecazfd'; 'o82', 'ecazfk'};
    subjT{13,2} = temp;
    clear temp

    subjT{14,1} = 'EDMM';
    temp.day = {'7_9';'7_12';'7_15';'7_17';'7_19'};
    temp.files{1,1} = {'qs', 'edmmaa';
        'nw1', 'edmmae'; 'nw2', 'edmmaf';
        'zt1', 'edmmab'; 'zt2', 'edmmai';
        'ga1', 'edmmac'; 'ga2', 'edmmah'};
    temp.files{2,1} = {'qs', 'edmmba';
        'nw1', 'edmmbd'; 'nw2', 'edmmbl';
        'zt1', 'edmmbe'; 'zt2', 'edmmbk';
        'ga1', 'edmmbf'; 'ga2', 'edmmbj';
        'o41', 'edmmbg'; 'o42', 'edmmbi'};
    temp.files{3,1} = {'qs', 'edmmca';
        'nw1', 'edmmcc'; 'nw2', 'edmmcm';
        'zt1', 'edmmcf'; 'zt2', 'edmmci';
        'ga1', 'edmmcg'; 'ga2', 'edmmch';
        'o41', 'edmmcd'; 'o42', 'edmmcl';
        'o81', 'edmmce'; 'o82', 'edmmck'};
    temp.files{4,1} = {'qs', 'edmmda';
        'nw1', 'edmmdh'; 'nw2', 'edmmdi';
        'zt1', 'edmmde'; 'zt2', 'edmmdm';
        'ga1', 'edmmdf'; 'ga2', 'edmmdl';
        'o41', 'edmmdd'; 'o42', 'edmmdn';
        'o81', 'edmmdg'; 'o82','edmmdk'};
    temp.files{5,1} = {'qs', 'edmmea';
        'nw1', 'edmmed'; 'nw2', 'edmmeo';
        'zt1', 'edmmee'; 'zt2', 'edmmen';
        'ga1', 'edmmeh'; 'ga2', 'edmmel';
        'o41', 'edmmeg'; 'o42', 'edmmem';
        'o81', 'edmmej'; 'o82','edmmek'};
    subjT{14,2} = temp;
    clear temp

    subjT{15,1} = 'EEPM';
    temp.day = {'7_24';'7_26';'7_29';'8_2';'8_5';'8_7'};
    temp.files{1,1} = {'qs', 'eepmaa';
        'nw1', 'eepmad'; 'nw2', 'eepmae';
        'zt1', 'eepmac'; 'zt2', 'eepmaf';
        'ga1', 'eepmab'; 'ga2', 'eepmag'};
    temp.files{2,1} = {'qs', 'eepmbb';
        'nw1', 'eepmbg'; 'nw2', 'eepmbh';
        'zt1', 'eepmbe'; 'zt2', 'eepmbj';
        'ga1', 'eepmbd'; 'ga2', 'eepmbk';
        'o41', 'eepmbf'; 'o42', 'eepmbi'};
    temp.files{3,1} = {'qs', 'eepmca';
        'nw1', 'eepmci'; 'nw2', 'eepmcj';
        'zt1', 'eepmcg'; 'zt2', 'eepmcl';
        'ga1', 'eepmcf'; 'ga2', 'eepmcm';
        'o41', 'eepmce'; 'o42', 'eepmcn';
        'o81', 'eepmch'; 'o82', 'eepmck'};
    temp.files{4,1} = {'qs', 'eepmdh';
        'nw1', 'eepmdi'; 'nw2', 'eepmdt';
        'zt1', 'eepmdj'; 'zt2', 'eepmds';
        'ga1', 'eepmdk'; 'ga2', 'eepmdr';
        'o41', 'eepmdo'; 'o42', 'eepmdp';
        'o81', 'eepmdn'; 'o82', 'eepmdq'};
    temp.files{5,1} = {'qs', 'eepmea';
        'nw1', 'eepmed'; 'nw2', 'eepmem';
        'zt1', 'eepmeg'; 'zt2', 'eepmej';
        'ga1', 'eepmee'; 'ga2', 'eepmel';
        'o41', 'eepmeh'; 'o42', 'eepmei';
        'o81', 'eepmef'; 'o82', 'eepmek'};
    temp.files{6,1} = {'qs', 'eepmfa';
        'nw1', 'eepmfc'; 'nw2', 'eepmfl';
        'zt1', 'eepmff'; 'zt2', 'eepmfi';
        'ga1', 'eepmfe'; 'ga2', 'eepmfj';
        'o41', 'eepmfd'; 'o42', 'eepmfk';
        'o81', 'eepmfg'; 'o82', 'eepmfh'};
    subjT{15,2} = temp;
    clear temp
end